### ISSUE TITLE
Prism or CoreProtect

### ISSUE THREAD

**Issue by Leopere** [andune/heimdall#2]
Logblock is horrendously out of date these days.  I don't mind running logblock and CoreProtect or Prism but both of these plugins have webgui's and all that.  I have some guys who might be interested in helping you add this functionality.

**Comment by andune** [comment]
Should be pretty simple if the block log plugin offers an easily accessible API. You just need to write an implementation of BlockHistoryManager for said plugin, you can use the one for LogBlock as an example:

https://github.com/andune/heimdall/blob/master/src/main/java/org/morganm/heimdall/blockhistory/BlockHistoryLogBlock.java

And then modify the Factory to be able to find and load your history manager:

https://github.com/andune/heimdall/blob/master/src/main/java/org/morganm/heimdall/blockhistory/BlockHistoryFactory.java

Should be all that's needed. I would be happy to incorporate pull requests for history managers for additional block logging plugins.

**Comment by andune** [comment]
close as fixed via issue #5
