### ISSUE TITLE
Prism/Coreprotect Compat

### ISSUE THREAD

**Issue by Leopere** [andune/heimdall#5]
How hard would it be to get this capability.  I have a few developers that may be interested in offering a PR or something to update this if its not going to be a huge problem Log block at this point is hugely inefficient.  The aforementioned two block logging systems are much more up to date.

I cant find the github with an arbitrary search using the github search for core protect but here is the prism git. 

https://github.com/prism/Prism 

give me a heads up and I'll see what my devteam can figure out.

**Comment by andune** [comment]
I added it a week or two ago, but I don't run Prism and haven't had a chance to setup a test server to test it. So support is already there, it's completely untested and probably has some bugs.

https://github.com/andune/heimdall/blob/master/src/main/java/com/andune/heimdall/blockhistory/BlockHistoryPrism.java

You can checkout the source and run 'mvn package' to get your own copy of a dev build of Heimdall with Prism support. Feel free to test it out and report any success/bugs here.

**Comment by Leopere** [comment]
brilliant I cant wait to get back into town to try this I will report back asap.

**Comment by Leopere** [comment]
It does seem to be working ok with prism.  Though its getting a little bit spammy.

**Comment by andune** [comment]
Closing this issue as the last update states it is working with Prism, which my own testing now verifies. Please open additional tickets for any other issues.
